name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Encryption Service
      id: encryption-service
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Encryption Service
        setup-command: sudo apt-get update && sudo apt-get install -y apt-transport-https
          && sudo apt-get update && sudo apt-get install -y dotnet-sdk-8.0
        command: DOTNET_CLI_HOME=/tmp/ dotnet test ./CSharpAssessment --filter "Service=EncryptionService"
        timeout: 10
        max-score: 100
    - name: Processing Service
      id: processing-service
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Processing Service
        setup-command: sudo apt-get update && sudo apt-get install -y apt-transport-https
          && sudo apt-get update && sudo apt-get install -y dotnet-sdk-8.0
        command: dotnet test ./CSharpAssessment --filter "Service=ProcessingService"
        timeout: 10
        max-score: 100
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        ENCRYPTION-SERVICE_RESULTS: "${{steps.encryption-service.outputs.result}}"
        PROCESSING-SERVICE_RESULTS: "${{steps.processing-service.outputs.result}}"
      with:
        runners: encryption-service,processing-service
